platform :ios, ‘8.0’

target 'weibo-2' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  
  use_frameworks!

  pod 'SnapKit', '0.18.0'
  pod 'SVProgressHUD', '1.1.3'
  pod 'AFNetworking'
  pod 'SDWebImage'



end

